apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:
  app: redis
resources:
- redis-deployment.yaml
- redis-service.yaml
images:
- name: redis
  newName: redis
  newTag: alpine
