apiVersion: v1
kind: Service
metadata:
  labels:
    app: portfolio
  name: portfolio-service
spec:
  ports:
  - port: 8080
    targetPort: 8080
  selector:
    app: portfolio
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: portfolio
  name: portfolio
spec:
  replicas: 1
  revisionHistoryLimit: 3
  selector:
    matchLabels:
      app: portfolio
  template:
    metadata:
      labels:
        app: portfolio
    spec:
      containers:
      - image: simon7426/vue-portfolio-kubernetes:04c5f7b
        name: portfolio
        ports:
        - containerPort: 8080
