apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:
  app: portfolio
resources:
- portfolio-frontend-deployment.yaml
- portfolio-frontend-service.yaml
images:
- name: simon7426/vue-portfolio-kubernetes
  newTag: "0.4"
